import { Inter } from 'next/font/google';
import './globals.css';
require('@solana/wallet-adapter-react-ui/styles.css');
import NavBar from '@/components/Navbar';
import SolanaWalletProvider from '@/context/WalletProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SolanaWalletProvider>
          <NavBar />
          {children}
        </SolanaWalletProvider>
      </body>
    </html>
  );
}
